config/routes.rb
Rails.application.routes.draw do
  # Sign Up Routes (users)

  get "/signup" => "users#new"
  post "/users" => "users#create"

  # Login Routes (sessions)

  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"

  # Profile routes

  # get "/profiles" => "profiles#index"
  get "/profiles" => "profiles#show"
  
  get "/profiles/new" => "profiles#new"
  post "/profiles" => "profiles#create"
  
  get "/profiles/edit" => "profiles#edit", as: "edit_profile"

  patch "/profiles" => "profiles#update"

  # Post routes

  get "/posts/new" => "posts#new"
  get "/posts/:id" => "posts#show"
  post "/posts" => "posts#create"
  get "/posts/:id/edit" => "posts#edit"
  patch "/posts" => "posts#update"
  delete "/posts/:id" => "posts#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :profile
  belongs_to :user
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :posts 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :profiles
  has_many :posts

  has_secure_password
  validates :email, presence: true, uniqueness: true
  validates :username, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authenticate_user
    redirect_to "/login", status: :see_other unless current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :authenticate_user

  def show
    @post = Post.find_by(id: params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(
      user_id: current_user.id,
      profile_id: current_user.profiles[0].id,
      post_image: params[:post][:post_image],
      caption: params[:post][:caption],
    )
    @post.save!
    redirect_to "/profiles" 
  end

  def destroy
    post = Post.find_by(id: params[:id])
    post.destroy
    redirect_to "/profiles"
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  
  before_action :authenticate_user

  skip_before_action :verify_authenticity_token, only: [:update]
  
  def profile_params
    params.require(:profile).permit(:profile_picture, :bio)
  end

  def show
    @profile = Profile.find_by(user_id: current_user.id)
    @posts = current_user.posts.order(created_at: :desc)
    @post = Post.new
  end 

  def new
    @profile = Profile.new
    render :new
  end

  def create
    @profile = Profile.create(
      profile_picture: params[:profile][:profile_picture],
      bio: params[:profile][:bio],
      user_id: current_user.id,
    )
    @profile.save!
    redirect_to "/profiles"
  end

  def edit
    @profile = Profile.find_by(user_id: current_user.id)
  end

  def update
    @profile = Profile.find_by(user_id: current_user.id)
    if @profile.update(profile_params)
      @profile.save!
      redirect_to "/profiles"
    else
      render :edit
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    render template: "sessions/new"
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
  
      redirect_to "/profiles"
    else
      render json: {message: "Incorrect email or password. Try again"}
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to "/login"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render template: "users/new"
    # render json: {message: "testing new IG user action"}
  end

  def create
    @user = User.new(
      email: params[:user][:email],
      full_name: params[:user][:full_name],
      username: params[:user][:username],
      password: params[:user][:password],
      password_confirmation: params[:user][:password_confirmation],
    )
    if @user.save
      session[:user_id] = @user.id
      redirect_to "/profile/new"
    else
      render :new, status: :unprocessable_entity
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>InstaClone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">

  </head>

  <body style="padding: 80px 150px 50px;">

   <nav class="navbar navbar-expand-lg bg-white">
    <div class="container-fluid">
      <a class="navbar-brand" href="/profiles" style="color: black;">InstaClone</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto me-0 mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Profile
          </a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <li><a class="dropdown-item" href="/logout">Log Out</a></li>
            <% else %>
              <li><a class="dropdown-item" href="/login">Log In</a></li>
              <li><a class="dropdown-item" href="/signup">Sign Up</a></li>
            <% end %>
          </ul>
        </li>
      </ul>   
    </div>
  </nav>

<style>
  .navbar {
    background-color: white;
    color: black;
  }
  
  .navbar-brand {
    color: black;
  }
  
  .navbar-toggler-icon {
    background-image: url("data:image/svg+xml,%3Csvg viewBox='0 0 30 30' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0,0,0,.5)' stroke-width='2' stroke-linecap='round' stroke-miterlimit='10' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E");
  }
  
  .nav-link {
    color: black;
  }
  
  .dropdown-menu {
    background-color: white;
    color: black;
    border: none;
  }

  @media (max-width: 991px) {
  .hamburger-menu {
    display: block;
  }
}
</style>
   
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>

    <%= yield %>

    <script>
      document.querySelector('.hamburger-menu').addEventListener('click', () => {
        document.querySelector('.navbar-toggler').click();
      });
    </script>
  </body>
</html>

app/views/posts/new.html.erb
<%= form_with model: @post, url: "/posts", method: :post do |form| %>
  <%= form.label :post_image %>
  <%= form.text_field :post_image %>
  
  <%= form.label :caption %>
  <%= form.text_field :caption %>

  <%= form.submit "Create Post" %>
<% end %>

app/views/posts/show.html.erb
<div class="container">
  <% if @post %>
    <div class="card my-4">
      <%= image_tag @post.post_image, class: "card-img-top" %>
      <div class="card-body text-center">
        <p class="card-text"><%= @post.caption %></p>
        <div class="button-container">
          <a href="/posts/<%= @post.id %>/edit" class="btn btn-primary">Edit Post</a>
          <a href="/posts/<%= @post.id %>" data-turbo-method="delete" class="btn btn-danger">Delete Post</a>
        </div>
      </div>
    </div>
  <% else %>
    <p>Post not found</p>
  <% end %>
</div>

<style>

.card {
  max-width: 700px;
  margin: 0 auto;
  border: 1px solid #000;
  box-shadow: 0px 4px 4px rgba(0, 0, 0, 0.25);
}

.card-img-top {
  height: 400px;
  object-fit: cover;
}

.card-text {
  font-size: 24px;
  margin-bottom: 10px;
}

.button-container {
  display: flex;
  justify-content: center;
  gap: 10px;
}



</style>

app/views/profiles/edit.html.erb
<%= form_with(model: @profile, url: profiles_path, method: :patch, local: true) do |form| %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
  <%= form.label :profile_picture %>
  <%= form.text_field :profile_picture %>

  <%= form.label :bio %>
  <%= form.text_area :bio %>

  <%= form.submit "Save Changes", class: "btn btn-primary" %>
<% end %>

app/views/profiles/new.html.erb
<%= form_with(model: @profile, local: true) do |form| %>
  
  <%= form.label :profile_picture %>
  <%= form.text_field :profile_picture %>

  <%= form.label :bio %>
  <%= form.text_area :bio %>

  <%= form.submit "Save Changes", class: "btn btn-primary" %>
<% end %>

</div>

app/views/profiles/show.html.erb
<div class="profile-container">
  <img src="<%= @profile.profile_picture %>" class="profile-picture" /> 

  <div style="padding-top: 10px">
    <p><%= @profile.user.username%> </p>
  </div>

  <div style="padding-top: 2px">
    <%= simple_format(@profile.bio) %>
  </div>

  <div class="button-container">
    <a href="/profiles/edit<%= @profile %>" class="red-button">Edit Profile</a>
    <a href="/posts/new" class="red-button" style="margin-left: 10px;">New Post</a>
  </div>


</div>

<hr>

<div class="container mt-4">
  <div class="row">
    <% @posts.order(created_at: :desc).each do |post| %>
      <div class="col-md-4 col-sm-6 mb-4">
        <a href="/posts/<%= post.id %>">
          <div class="card square-card">
            <img src="<%= post.post_image %>" class="card-img-top square-card-img" alt="...">
            <div class="card-body">
            </div>
          </div>
        </a>
      </div>
    <% end %>
  </div>
</div>


<style>
.profile-container {
  text-align: center;
}

.profile-picture {
  border-radius: 50%;
  width: 175px;
  height: 175px;
  object-fit: cover;
}

.square-card {
  width: 100%;
  height: 0;
  padding-bottom: 100%;
  position: relative;
}

.square-card-img {
  width: 100%;
  height: 100%;
  object-fit: cover;
  position: absolute;
  top: 0;
  left: 0;
}


.card .card-body {
  position: absolute;
  bottom: 0;
  width: 100%;
}

.red-button {
    background-color: rgb(255, 90, 95);
    color: white;
    border: none;
    padding: 10px 20px;
    font-size: 1em;
    cursor: pointer;
    transition: background-color 0.3s;
    border-radius: 5px;
    width: 135px;
  }

  .red-button:hover {
    background-color: darkred;
  }

  .button-container {
  display: flex;
  justify-content: center;
  gap: 10px;
  padding-top: 10px;
  }
</style>

app/views/users/new.html.erb
<div class="page-container">
  <div class="signup-container">
    <div class="signup-header">
      <center><h4 class="tagline">Capture + Share</h4></center>
      <center><p class="subheading">sign up to see photos and videos from your friends and join our community</p></center>
    </div>

    <%= form_with model: @user do |form| %>
      
      
      <div class="form-floating mb-1" style="padding-top: 7px">
        <%= form.email_field :email, class: "form-control", id: "floatingInput", placeholder: "Email Address" %>
        <label for="floatingInput">Email Address</label>
      </div>

      <div class="form-floating mb-1" style="padding-top: 7px">
        <%= form.text_field :full_name, class: "form-control", id: "floatingFullName", placeholder: "Full Name" %>
        <label for="floatingFullName">Full Name</label>
      </div>

      <div class="form-floating mb-1" style="padding-top: 7px">
        <%= form.text_field :username, class: "form-control", id: "floatingUsername", placeholder: "Username" %>
        <label for="floatingUsername">Username</label>
      </div>

      <div class="form-floating mb-1" style="padding-top: 7px">
        <%= form.password_field :password, class: "form-control", id: "floatingPassword", placeholder: "Password" %>
        <label for="floatingPassword">Password</label>
      </div>

      <div class="form-floating mb-1" style="padding-top: 7px">
        <%= form.password_field :password_confirmation, class: "form-control", id: "floatingPasswordConfirmation", placeholder: "Password Confirmation" %>
        <label for="floatingPasswordConfirmation">Password Confirmation</label>
      </div>

      <div class="form-group" style="padding-top: 7px">
        <%= form.submit "Sign Up", class: "red-button" %>
      </div>

      <div class="option" style="padding-top: 7px">
        <center><p>Have an account? <a href="">Log In</a></p></center>
      </div>
    <% end %>
  </div>
</div>

<style>
  html, body {
    height: 100%;
    margin: 0;
  }

  .signup-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    max-width: 400px;
    margin-top: 25px;
    border: 2px solid #999; /* Add border */
    padding: 20px; /* Add padding */
    border-radius: 10px; /* Add rounded corners */
  }

  .page-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    width: 100%;
    margin-top: 5px;
  }


  .form-group {
    display: flex;
    flex-direction: column;
    align-items: center;
    width: 100%;
    padding: 7px;
  }

  .red-button {
    background-color: rgb(255, 90, 95);
    color: white;
    border: none;
    padding: 10px 20px;
    font-size: 1em;
    cursor: pointer;
    transition: background-color 0.3s;
    border-radius: 5px;
    width: 135px;
  }

  .red-button:hover {
    background-color: darkred;
  }
</style>